#! /bin/sh

set -e

case "$1" in
start)
    echo -n "Starting sdcard daemon: "
    start-stop-daemon -S -b -a /usr/bin/sdcard
    if [ -x /data/helloworld ]
    then
    start-stop-daemon -S -b -a /data/helloworld
    else
    start-stop-daemon -S -b -a /usr/bin/helloworld
    fi
    if [ -x /data/monitor.sh ]
    then
    /data/monitor.sh &
    fi
    start-stop-daemon -S -b -a /usr/bin/aliyun
    start-stop-daemon -S -b -a /usr/bin/ssl
    echo "done"
    ;;
  stop)
    echo -n "Stopping sdcard daemon: "
    start-stop-daemon -K -n sdcard
    start-stop-daemon -K -n helloworld
    start-stop-daemon -K -n aliyun
    start-stop-daemon -K -n ssl
    echo "done"
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage sdcard { start | stop | restart }" >&2
    exit 1
    ;;
esac

exit 0
