#! /bin/sh
#
#
# Init script for: qmi_shutdown_modem
USER=mdmuser
GROUP=mdmuser
DAEMON_PATH=/usr/bin/
DAEMON=qmi_shutdown_modem
set -e

case "$1" in
  start)
        echo "Starting $DAEMON" > /dev/kmsg
        start-stop-daemon -c $USER:$GROUP -S -b -x $DAEMON_PATH$DAEMON
        ;;
  stop)
        echo "Stopping $DAEMON" > /dev/kmsg
        start-stop-daemon -K -x $DAEMON
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage $0 { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
