#! /bin/sh
#
#
# Init script for: quectel_daemon
USER=mdmuser
GROUP=mdmuser
DAEMON_PATH=/usr/bin/
# quectel_daemon
# Changed to a script temporarily to trace logs
DAEMON=start_quec_daemon
set -e

case "$1" in
  start)
        echo "Starting $DAEMON" > /dev/kmsg
        start-stop-daemon -c $USER:$GROUP -S -b -x $DAEMON_PATH$DAEMON
        ;;
  stop)
        echo "Stopping $DAEMON" > /dev/kmsg
        start-stop-daemon -K -x $DAEMON
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage $0 { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0

#  ---------------------------------------------------------------------------
#   Copyright (c) 2012 Qualcomm Technologies, Inc.  All Rights Reserved.
#   Qualcomm Technologies Proprietary and Confidential.
#  ---------------------------------------------------------------------------
#

#! /bin/sh
#
# init.d script for quectel daemon

set -e

case "$1" in
       start)
                echo -n "Starting quectel_daemon: "
                start-stop-daemon -c mdmuser:mdmuser -S -b -a /usr/bin/start_quec_daemon
                echo "done"
                ;;
       stop)
                echo -n "Stopping quectel daemon: "
                start-stop-daemon -K -n quectel_daemon
                echo "done"
                ;;
       restart)
                $0 stop
                $0 start
                ;;
       *)
                echo "Usage: quectel_daemon { start | stop | restart }" >&2
                exit 1
                ;;
esac

exit 0
