#!/bin/sh
#
#Copyright (c) 2013 Qualcomm Technologies, Inc.  All Rights Reserved.
#Qualcomm Technologies Proprietary and Confidential.

# Location launcher service  init.d script to start the Location Software's mcmlocserver daemon

set -e

case "$1" in
  start)
        # create required directories for location services
        if [ ! -d /data/misc/location/mq ]
        then
            mkdir -p /data/misc/location/mq
        fi
        if [ ! -d /data/misc/location/xtwifi ]
        then
            mkdir -p /data/misc/location/xtwifi
        fi
        echo -n "Starting Location Launcher Services: "
        start-stop-daemon -S -b -a /usr/bin/loc_launcher
        echo "done"
        ;;
  stop)
        echo -n "Stopping Location launcher Services: "
        start-stop-daemon -K -n loc_launcher
        echo "done"
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage loc_launcher { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
