#! /bin/sh
#
#
# Init script for: loc_launcher
# Location launcher service  
# Location Software's mcmlocserver daemon
USER=mdmuser
GROUP=mdmuser
DAEMON_PATH=/usr/bin/
DAEMON=loc_launcher
set -e
if [ ! -d /data/misc/location/mq ]
then
      mkdir -p /data/misc/location/mq
fi
if [ ! -d /data/misc/location/xtwifi ]
then
      mkdir -p /data/misc/location/xtwifi
fi

case "$1" in
  start)
        echo "Starting $DAEMON" > /dev/kmsg
        start-stop-daemon -c $USER:$GROUP -S -b -x $DAEMON_PATH$DAEMON
        ;;
  stop)
        echo "Stopping $DAEMON" > /dev/kmsg
        start-stop-daemon -K -x $DAEMON
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage $0 { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
