#! /bin/sh
#
#
# Init script for: QCMAP_ConnectionManager
USER=mdmuser
GROUP=mdmuser
DAEMON_PATH=/usr/bin/
DAEMON=QCMAP_ConnectionManager
set -e

case "$1" in
  start)
        echo "Starting $DAEMON" > /dev/kmsg
        start-stop-daemon -c $USER:$GROUP -S -b -a $DAEMON_PATH$DAEMON /data/mobileap_cfg.xml d
        ;;
  stop)
        echo "Stopping $DAEMON" > /dev/kmsg
        start-stop-daemon -K -n $DAEMON
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage $0 { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
