#! /bin/sh
#
#
# Init script for: DS_MUX
# DS_MUX: Data Software's DS_MUX daemon

USER=mdmuser
GROUP=mdmuser
DAEMON_PATH=/usr/bin/
DAEMON=DS_MUX
DAEMON_OPT1_UART="1"
DAEMON_OPT2_UART="/dev/ttyHS1"
DAEMON_OPT1_USB="2"

set -e

case "$1" in
  start)
        echo "Starting $DAEMON" > /dev/kmsg
        start-stop-daemon -c $USER:$GROUP -S -b -a $DAEMON_PATH$DAEMON -- $DAEMON_OPT1_UART $DAEMON_OPT2_UART
        ;;
  stop)
        echo "Stopping $DAEMON" > /dev/kmsg
        start-stop-daemon -K -n $DAEMON
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage $0 { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
