#! /bin/sh
#
#
# Init script for: time_daemon
USER=mdmuser
GROUP=mdmuser
DAEMON_PATH=/usr/bin/
DAEMON=time_daemon
set -e
mkdir -p /data/time/

case "$1" in
  start)
        echo "Starting $DAEMON" > /dev/kmsg
        start-stop-daemon -c $USER:$GROUP -S -b -n time_daemon -a $DAEMON_PATH$DAEMON
        ;;
  stop)
        echo "Stopping $DAEMON" > /dev/kmsg
        start-stop-daemon -K -n $DAEMON
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage $0 { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0
