#!/bin/sh
#
# Copyright (c) 2012-2015, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived from
#       this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT ARE DISCLAIMED.  IN NO
# EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# Start Modem's USB Gadget
# get soc platform to update product related information
num="0"
mode="hsusb"

pkill adbd

mkdir -p /dev/usb-ffs/adb
mount -o uid=2000,gid=2000 -t functionfs adb /dev/usb-ffs/adb
mount -o remount,gid=5,mode=620 /dev/pts
echo hsusb > /sys/bus/platform/devices/usb_bam/enable
echo 0 > /sys/class/android_usb/android0/enable
echo 0125 > /sys/class/android_usb/android0/idProduct
echo 27C7 > /sys/class/android_usb/android0/idVendor
echo diag > /sys/class/android_usb/android0/f_diag/clients
echo 239 > /sys/class/android_usb/android0/bDeviceClass
echo 2 > /sys/class/android_usb/android0/bDeviceSubClass
echo 1 > /sys/class/android_usb/android0/bDeviceProtocol
# echo tty,smd,smd> /sys/class/android_usb/android0/f_serial/transports

echo smd,smd,smd,tty > /sys/class/android_usb/android0/f_serial/transports

echo QTI,BAM_DMUX > /sys/class/android_usb/android0/f_rmnet/transports
echo BAM_DMUX > /sys/class/android_usb/android0/f_usb_mbim/mbim_transports
# echo diag,serial,rmnet,ffs,audio > /sys/class/android_usb/android0/functions
echo diag,serial,rmnet,adb > /sys/class/android_usb/android0/functions
echo adb > /sys/class/android_usb/android0/f_ffs/aliases
echo 1 > /sys/class/android_usb/android0/remote_wakeup
echo 1 > /sys/class/android_usb/android0/f_rndis/wceis

echo diag,serial,rmnet,ffs > /sys/class/android_usb/android0/functions
# Quectel Wireless Solutions Co., Ltd. EC25 LTE modem
echo "Quectel Wireless Solutions Co., Ltd." > /sys/class/android_usb/android0/iManufacturer
echo "EC25 LTE modem" > /sys/class/android_usb/android0/iProduct
sleep 2
echo 1 > /sys/class/android_usb/android0/enable
/etc/init.d/adbd start
